version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.12.0
    steps:
      - checkout

      - run:
          name: Installing dependencies
          command: npm install

      - run:
          name: Building
          command: npm run build

      - store_artifacts:
          path: ./dist
          destination: artifacts

workflows:
  version: 2
  circlecli_demo:
    jobs:
      - build:
          filters:
            branches:
              only: master
